; ========================================================================================================================
; * Created by: Holtek Touch MCU Workshop, Version 3.5.0.0
; USER_PROGRAM.inc
; 03:02:23 PM Saturday, December 16, 2017
; ========================================================================================================================
#include "..\TKS_GLOBE_VARIES.inc" 
#include "..\BS84B08A_LIBV413\BS84B08A_LIBV413.aex" 
#include "..\MAIN_PROGRAM_V104\MAIN_PROGRAM_V104.aex" 
#include "..\LEDX4_V16\LEDX4_V16.aex" 
